apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ig63cddu3-go-gitops
  description: This is GitOps manifest for ig63cddu3-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ig63cddu3-go
    janus-idp.io/tekton: ig63cddu3-go
    backstage.io/kubernetes-id: ig63cddu3-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ig63cddu3-go
